version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ${AGENT_MONITOR_DIR:-.}/tes_crons:/opt/agent_monitor/crons
    environment:
      - PYTHONUNBUFFERED=1
